### ISSUE TITLE
Setup demo for `matcher-cli`

### ISSUE THREAD

**Issue by rexagod** [publiclab/matcher-cli#1]
@jywarren I've made a CLI demo for `matcher-cli`. Let me know what you think!

Also, I will be documenting this repository very soon, along with core, and the command below is to just give the users a preview of how the matcher works. Try it out and let me know what do you think!

```
bash <(curl -s https://gist.githubusercontent.com/rexagod/6e1a2cfdc18e1b12ff8d64b5d4e6985a/raw/bfe011cfecc2c7777bc3d161a064f2bf924fdbfb/cli-demo.sh)

```

**Comment by jywarren** [comment]
Awesome!!!!!!!

**Comment by rexagod** [comment]
@jywarren I just noticed a bug in this one. Please use the one below instead. Updated the README too.

```
bash <(curl -s https://gist.githubusercontent.com/rexagod/6e1a2cfdc18e1b12ff8d64b5d4e6985a/raw/e5cf33c9bb2427f25d8394d0e007cabc40a8a5da/cli-demo.sh)
```

Edit: Updated again. It should work fine now.
