### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jywarren** [publiclab/matcher-cli#6]
Hi @rexagod - we have a general policy of GPLv3, do you think you could re-license these under GPL? Thank you!

**Comment by rexagod** [comment]
Done! Should I make the same changes for `matcher-core` as well?

**Comment by jywarren** [comment]
That would be super!

**Comment by rexagod** [comment]
Both libraries shifted from `BSD-2-Clause` to `GNU-General-Public-License-v3.0`.

**Comment by jywarren** [comment]
awesome!!!
